### ISSUE TITLE
New feature -- Wled

### ISSUE THREAD

**Issue by qianwen00** [sui001/Art-Art-Art#6]
Since the client has put forward new requirements, it is necessary to implement a new function that applies wled. In the end, it is necessary to display different animation effects through real-time transmission of data on five 2m*2m curtains (20*20 LEDs).

Currently, the hardware of the chip loaded with wled is controlled by entering the corresponding IP address on the wled app, thereby controlling the LED matrix connected to the chip to achieve different LED lighting effects.

So for this requirement, we need to write a program to send commands to the WLED device through the network to control the visual presentation of the LED.

**Comment by joe61fa6f1awe** [comment]
Same as WLED coding
